security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                success_handler: App\Redirection\AfterLoginRedirection
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: dashboard

            logout:
                path: logout
                target: /
                success_handler: App\Redirection\AfterLogoutRedirection
            anonymous:    true
            switch_user: { role: ROLE_ADMIN, parameter: _switch_user }

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
